cds-snc/cloud-based-sensor

- README.md
Fix the ConfigRule links in the main README.
> docs: fix links to ConfigRules

- .github/workflows/terragrunt-apply-central.yml
- .github/workflows/terragrunt-apply-satellite.yml
- .github/workflows/terragrunt-plan-central.yml
- .github/workflows/terragrunt-plan-satellite.yml
- terragrunt/.env_example
- terragrunt/aws/central_account/iam.tf
- terragrunt/aws/central_account/inputs.tf
- terragrunt/aws/central_account/kms.tf
- terragrunt/aws/central_account/s3.tf
- terragrunt/env/terragrunt.hcl
This will be assumed by the CBS agent to read objects that
are replicated to the log archive bucket.
* Closes #1
> feat: role to read from log archive bucket

- .github/workflows/terragrunt-apply-satellite.yml
- .github/workflows/terragrunt-plan-satellite.yml
- terragrunt/aws/cloudtrail/cloudtrail.tf
- terragrunt/env/satellite/cloudtrail/terragrunt.hcl
- terragrunt/env/satellite/config/terragrunt.hcl
1. Create a multi region Trail that logs all events to the S3 satellite bucket.
1. Update Terraform satellite workflows to plan/apply the CloudTrail.
1. Add dependency ordering between the satellite account modules.
* Closes #32
* #3
> feat: add CloudTrail that logs to satellite S3 bucket

- .github/workflows/compliance-check.yml
- .github/workflows/retrieve-accounts.yml
- .github/workflows/terragrunt-apply-central.yml
- .github/workflows/terragrunt-apply-satellite.yml
- .github/workflows/terragrunt-plan-central.yml
- .github/workflows/terragrunt-plan-satellite.yml
Add a workflow that will check all satellite account CBS ConfigRules and
post a Slack message if any are non-compliant.
Also creates a shared `retrieve-accounts.yml` workflow to generate the
matrix config used by the satellite account workflows.
* Closes #38
> feat: check satellite ConfigRule compliance

- .github/workflows/terragrunt-apply-central.yml
- .github/workflows/terragrunt-plan-central.yml
Enable the GitHub workflows to Terraform plan/apply the central account resources.
* #40
> feat: enable Central Terraform plan/apply

- .github/workflows/compliance-check.yml
Assume the satellite account role to check the compliance
status of its ConfigRules.
* #47 
* #38
> fix: compliance check workflow

- README.md
- bootstrap/central_account_iam/bootstrap.sh
Includes overview and refined setup commands.
Here's a link to the [README.md in the PR branch](https://github.com/cds-snc/cloud-based-sensor/blob/docs/readme/README.md).
> docs: update main README with more info

- terragrunt/aws/config/s3_access_logs.tf
Fix to use the correct IAM permission.
> fix: correct iam permission

- terragrunt/aws/config/s3_access_logs.tf
It'd be helpful if the lambda could actual submit it's config evaluations. This will fix that!
> fix: final final fix of iam

- terragrunt/aws/config/elb_logs.tf
- terragrunt/aws/config/vpc_flow_logs.tf
Check for ELB and VPC logging
Closes #4
Closes #7
> feat: elb and vpc log config rules

- terragrunt/aws/config/cloudtrail.tf
Add compliance ConfigRule to check that CloudTrail is enabled
and logging to the S3 satellite bucket.
* Closes #3
> feat: CloudTrail enabled ConfigRule

- .github/workflows/compliance-check.yml
Adds the CloudTrail, ELB, WAF and VPC ConfigRules to the compliance checking workflow.
> chore: add new config rules to compliance workflow

- terragrunt/aws/config/config_rules/s3_access_logs/s3_access_logs_rule.py
- terragrunt/aws/config/config_rules/s3_access_logs/s3_access_logs_rule_test.py
Update the S3 access log ConfigRule so that a bucket that is
an access log destination for another bucket is marked as
not applicable.
The presence of the canned AWS `log-delivery-write` ACL is used
to determine if a bucket is used for access logging.
* Closes #76
> fix: S3 access log buckets should not log

- .devcontainer/Dockerfile
Fix the AWS cli command autocomplete in the devcontainer.
> fix: devcontainer AWS CLI autocomplete

- .github/workflows/compliance-check.yml
This will make it obvious in the workflow history when an account
has failed its daily compliance check.
> feat: fail compliance when account not compliant

- .github/workflows/compliance-check.yml
Disabling the compliance check until the onboarded product
PRs are merged.
> chore: disable compliance check

- terragrunt/aws/central_account/iam.tf
Renames the role assumed by CCCS to the expected name.
> feat: rename log archive read role

- .github/workflows/terragrunt-apply-central.yml
- .github/workflows/terragrunt-apply-satellite.yml
- .github/workflows/terragrunt-plan-central.yml
- .github/workflows/terragrunt-plan-satellite.yml
- terragrunt/aws/alarms/billing_alarm.tf
- terragrunt/aws/alarms/inputs.tf
- terragrunt/aws/alarms/kms.tf
- terragrunt/aws/alarms/sns.tf
- terragrunt/env/central/alarms/.terraform.lock.hcl
- terragrunt/env/central/alarms/terragrunt.hcl
- terragrunt/env/common/provider.tf
- terragrunt/env/satellite/alarms/.terraform.lock.hcl
- terragrunt/env/satellite/alarms/terragrunt.hcl
Add a CloudWatch alarm, SNS topic and Slack notification Lambda
for estimated billing changes that are greater than a percentage
change threshold in a six hour period.
Note that billing alerts must be enabled on the payer account
for the `EstimatedCharges` metric to be available in CloudWatch.
* Closes #111
> feat: CloudWatch alarm for billing changes

- terragrunt/aws/alarms/billing_alarm.tf
- terragrunt/aws/alarms/inputs.tf
- terragrunt/env/satellite/alarms/terragrunt.hcl
Test whether anomaly detection will make it easier to determine if there is a large increase in AWS costs related to cbs onboarded products.
> feat: billing anomaly detection

- terragrunt/aws/cloudtrail/cloudtrail.tf
Step one to removing extra cloudtrail...trail.
> Removal of cloudtrail.tf to kick off cloudtrail removal - The Sphinx

- .github/workflows/terragrunt-apply-central.yml
- .github/workflows/terragrunt-apply-core.yml
- .github/workflows/terragrunt-apply-satellite.yml
- .github/workflows/terragrunt-plan-central.yml
- .github/workflows/terragrunt-plan-core.yml
- .github/workflows/terragrunt-plan-satellite.yml
Use the CDS Terraform Tools github action to setup Terraform, Terragrunt and Conftest.
> chore: upgrade workflows to terraform tools action

- bootstrap/central_account_iam/main.tf
- terragrunt/aws/alarms/sns.tf
- terragrunt/aws/central_account/main.tf
- terragrunt/aws/central_account/s3.tf
- terragrunt/aws/satellite_bucket/s3.tf
Changing the terraform module reference link to be consistent with the terraform documentation - https://developer.hashicorp.com/terraform/language/modules/sources#modules-in-package-sub-directories
> Changing the terraform module reference

- terragrunt/aws/central_account/main.tf
> fix: remove the unnecessary iam policy

- terragrunt/aws/central_account/iam.tf
- terragrunt/aws/central_account/kms.tf
Adding the new role to the permission principals
> fix: add the new role to the principals
