bootstrap/satellite_account_iam/main.tf
bootstrap/satellite_account_iam/variables.tf
terragrunt/aws/cloudtrail/cloudtrail.tf
terragrunt/aws/config/iam.tf
terragrunt/aws/config/s3_satellite_bucket.tf

1. Update the resource names to make them easier to exclude in our AWS nuke config that runs weekly against scratch accounts.
2. Fix CloudTrail creation by making it depend on S3 bucket policy.
3. Update satellite bootstrap to get AWS account ID from the `aws_caller_identity` data element.
* #9

feat: consistent resource names for AWS nuke exclude

---

bootstrap/satellite_account_iam/main.tf

Use the `AdministratorAccess` for the role assumed by the `CbsCentral` account when applying changes to satellite accounts.
This should scaled back to the required IAM permissions once we've finished adding resources.
* Closes #40

fix: switch to Admin for satellite Terraform role

---

.github/workflows/retrieve-accounts.yml
bootstrap/satellite_account_iam/bootstrap.sh

The `satellite_accounts` file should not have a `.json` file extension.
Once this common workflow is merged to main, we can update
the rest of the project files to reference the file without `.json`.
Once this is merged, it will break all workflows until the other references
to `satellite_accounts.json` are fixed.

fix: change to `satellite_accounts` without .json

---

terragrunt/aws/config/config_rules/s3_access_logs/README.md
terragrunt/aws/config/config_rules/s3_access_logs/s3_access_logs_rule.py
terragrunt/aws/config/config_rules/s3_access_logs/s3_access_logs_rule_test.py
terragrunt/aws/config/s3_access_logs.tf

Switching back to the custom lambda approach since the AWS provided S3 access logs config rule doesn't support the ability to exclude certain resources.

feat: switch back to custom lambda config rule for s3 access logs

---

terragrunt/aws/config/config_rules/s3_satellite_bucket/compliance/s3_satellite_bucket_rule.py
terragrunt/aws/config/config_rules/s3_satellite_bucket/compliance/s3_satellite_bucket_rule_test.py

Not providing the bucket name results in a `resource is unknown or has not been discovered` error. This will fix this situation when the rule is compliant. However when its not compliant this message will still be visible since the bucket doesn't exist. This is expected behaviour.

fix: provide bucket name as resource id

---

terragrunt/aws/config/config_rules/s3_access_logs/s3_access_logs_rule.py
terragrunt/aws/config/config_rules/s3_access_logs/s3_access_logs_rule_test.py

Omit the `cbs-satellite-$ACCOUNT_ID-access` bucket from the
ConfigRule check.
* Closes #45

fix: satellite S3 access log bucket should not log

---

terragrunt/aws/config/config_rules/wafv2_logs/webacl_logs_rule.py
terragrunt/aws/config/config_rules/wafv2_logs/webacl_logs_rule_test.py
terragrunt/aws/config/s3_access_logs.tf
terragrunt/aws/config/wafv2_logs.tf

No longer using config to remediate violations. This will be managed by terraform and flagged via a slack message

chore: remove autoremediate

---

.github/workflows/terragrunt-apply-central.yml
.github/workflows/terragrunt-apply-satellite.yml
.github/workflows/terragrunt-plan-central.yml
.github/workflows/terragrunt-plan-satellite.yml
.gitignore
terragrunt/env/central/central_account/.terraform.lock.hcl
terragrunt/env/satellite/cloudtrail/.terraform.lock.hcl
terragrunt/env/satellite/config/.terraform.lock.hcl
terragrunt/env/satellite/satellite_bucket/.terraform.lock.hcl

Update the Terraform path triggers for the Central and Satellite
workflows so they are only invoked when files related to their
resources are updated.
Also adds the `terraform.lock.hcl` to pin dependencies.

fix: Terraform workflow path triggers

---

README.md
bootstrap/central_account_iam/bootstrap.sh
bootstrap/satellite_account_iam/bootstrap.sh

Reworked section on ConfigRules, removed auto-remediation debugging and moved log archive bucket structure to the bottom ([updated README](https://github.com/cds-snc/cloud-based-sensor/blob/docs/readme-cleanup/README.md)).
Also adds the AWS account ID to the bootstrap script output:

docs: adjustments to README

---

.github/workflows/compliance-check.yml

With the IAM policies being tightened down in #70, the session
name needs to be updated to allow the central account to
continue to assume satellite account roles.

fix: update the assume role session name

---

terragrunt/aws/central_account/main.tf
terragrunt/aws/central_account/s3.tf
terragrunt/env/terragrunt.hcl

Tweak how the account number file is processed by Terragrunt. The quotes are necessary to generate the Github action workflow matrix, however that is causing terraform to escape the quotes when used within a formatted string.

fix: quotes are not required when processing in terraform

---

.github/workflows/compliance-check.yml
.github/workflows/terragrunt-apply-central.yml
.github/workflows/terragrunt-apply-satellite.yml
.github/workflows/terragrunt-plan-central.yml
.github/workflows/terragrunt-plan-satellite.yml
bootstrap/satellite_account_iam/variables.tf
terragrunt/env/satellite/satellite_bucket/terragrunt.hcl
terragrunt/env/terragrunt.hcl

This will prevent us from conflicting with the existing CbsCentral
auto-remediation rules.

chore: migrate to a new CBS central account

---

terragrunt/aws/central_account/s3.tf
terragrunt/aws/satellite_bucket/s3.tf

Update the two S3 access log buckets to use the correct module.
This will grant them the expected `log-delivery-write` ACL.
* #76

fix: set S3 logging buckets to correct module

---

terragrunt/aws/cloudtrail/cloudtrail.tf
terragrunt/aws/satellite_bucket/s3.tf

The satellite bucket policy will also require policy items for
log delivery from other AWS services.  To reflect this change, the
policy definition is being moved out of the CloudTrail module into
the `satellite_bucket` module.
The `satellite_bucket` Terraform state was updated locally to remove the policy with:
```sh
cd ./terragrunt/env/satellite/cloudtrail
terragrunt state rm aws_s3_bucket_policy.satellite_trail
```

fix: refactor satellite bucket policy

---

terragrunt/aws/satellite_bucket/s3.tf

This allows the satellite bucket to be used as the target
for another S3 bucket's access logging.
* Closes #83

chore: add S3 access log IAM policy

---

README.md

Minor docs adjustment since the `terragrunt import` command is no longer valid.
Updated doc section will look like so:
https://github.com/cds-snc/cloud-based-sensor/blob/docs/tg-import/README.md#central-account

docs: update Terraform state import command

---

bootstrap/central_account_iam/bootstrap.sh
bootstrap/satellite_account_iam/bootstrap.sh
bootstrap/scripts/put-bucket-logging.sh

Script that can be used to set S3 buckets in an account to
use the satellite bucket as the access log destination.
This fixes compliance of the `cbs_s3_bucket_logging_enabled`
ConfigRule.

feat: add put-bucket-logging script

---

.github/workflows/compliance-check.yml

This will post into the #cloud-based-sensor channel if
any accounts have resources that are marked as
`NON_COMPLIANT` by the conformance pack.

feat: enable compliance check workflow

---

README.md
bootstrap/scripts/put-bucket-logging.sh

This updated file structure for the log archive bucket is based
on the structure that AWS services provide their logs.
The new structure will be:
```
cbs-log-archive-bucket/
├─ [cloudtrail_logs]/
│  ├─ [AWSLogs]/
│  │  ├─ [aws_account_id]
│  │  │  ├─ file
│  │  │  ├─ ...
│  │  │  
├─ [elb_logs]/
│  ├─ [AWSLogs]/
│  │  ├─ [aws_account_id]
│  │  │  ├─ file
│  │  │  ├─ ...
│  │  │  
├─ [s3_access_logs]/
│  ├─ [AWSLogs]/
│  │  ├─ [aws_account_id]
│  │  │  ├─ file
│  │  │  ├─ ...
│  │  │  
├─ [vpc_flow_logs]/
│  ├─ [AWSLogs]/
│  │  ├─ [aws_account_id]
│  │  │  ├─ file
│  │  │  ├─ ...
│  │  │  
├─ [waf_acl_logs]/
│  ├─ [AWSLogs]/
│  │  ├─ [aws_account_id]
│  │  │  ├─ file
│  │  │  ├─ ...
```
In order to use this style the following will need to be updated in the satellite accounts:
* S3 access …

fix: update the log archive file structure

---

README.md
terragrunt/env/satellite/config/conformance_packs/cloud_based_sensor.yml

Updates the readme to reference the updated load balancer s3 logging path, as well as corrects the description for the load balancer config rule.

docs: update readme and load balancer rule description

---

terragrunt/aws/central_account/inputs.tf
terragrunt/aws/central_account/s3.tf
terragrunt/env/central/central_account/terragrunt.hcl

Add a notification to invoke the CBS transport lambda when
a new object is created in the log archive bucket.
The existing notification was imported locally, so there should be no planned changes.

feat: add log archive event notification

---

.github/workflows/terraform-security-scan.yml
terragrunt/aws/.checkov.yml
terragrunt/aws/config/wafv2_logs.tf

Fix the Terraform security scan GitHub workflow's path to the
Terraform files.  Also adds suppression comments for checks
we're not concerned with.

fix: path to the Terraform in the checkov action

---

terragrunt/aws/central_account/s3.tf
terragrunt/aws/satellite_bucket/s3.tf

This increases the log retention to 90 days in the satellite and
central log archive buckets, based on a recommendation from
CCCS.

feat: increase log retention to 90 days

---

.github/workflows/terragrunt-apply-central.yml
.github/workflows/terragrunt-plan-central.yml
terragrunt/aws/central_account/s3.tf
terragrunt/aws/cloudtrail/cloudtrail.tf
terragrunt/aws/cloudtrail/inputs.tf
terragrunt/env/central/cloudtrail/terragrunt.hcl

This will send CloudTrail logs directly to the log-archive bucket and be
used to watch for anomalies in the account.
* #116

feat: add CloudTrail to central account

---

terragrunt/aws/satellite_bucket/s3.tf

Update the S3 module version so that it is possible to control if
delete markers are replicated to the destination bucket.
By doing this, and not enabling delete marker replication, it means
a shorter object expiration of 14 days can be set on the satellite
bucket objects which will save storage costs.
The central log archive bucket will keep its 90 day object expire
lifecycle rule so we'll still have the logs if needed.
The unrelated changes to `136676205420` are from the CBS
auto-remediation rules which were disabled yesterday.
* cds-snc/terraform-modules#110

feat: set satellite bucket object expire to 14 days

---

terragrunt/env/common/provider.tf

The 4.x release of the provider contains breaking changes.

chore: pin AWS provider to 3.x

---

terragrunt/aws/alarms/billing_alarm.tf
terragrunt/aws/alarms/kms.tf
terragrunt/aws/alarms/sns.tf

Update the billing alarm resources to use the expected name
prefixes so they are not removed by the scratch account weekly
AWS nuke job.

fix: billing alarm resource names to skip AWS nuke

---

terragrunt/aws/alarms/billing_alarm.tf

Simple one line removal to quiet down the OK alarms telling us "IT'S OK NOW EVERYTHING IS OK."

remove ok_action from billing alarm

---

terragrunt/aws/alarms/billing_alarm.tf

1 line fix to adjust anomaly detection to alert not just higher costs, but to anomalous costs lower than expected as well. (PS the algo does in fact adjust for seasonality and usage, just as an added bonus.)

Added threshold to alert on both upper and lower boundary anomalies

---

terragrunt/aws/satellite_bucket/s3.tf

Ran into an error with the load balancer log not having permission to write to the logging bucket. Tracked it down to the IAM permission that was too specific and only allowed writing to the vpc_flow_logs directory.

fix: allow writing logs to other paths in log bucket

---

terragrunt/aws/alarms/billing_alarm.tf

Switching the statistic used to build the model to `average` value vs `maximum` (recommended for values that may not be flat), and increasing the standard deviation band from $2USD to $3USD.

Updating anomaly values to smooth out model

---

terragrunt/aws/alarms/billing_alarm.tf

Changing the period to 12 hours because according to AWS:
>The ML algorithm we use currently works well with dense data that exhibit seasonality and trends. In this case, since this metric is expected to have only 1 datapoint every 12 hours, this feature may not work well for this metric...(metric being 'billing' in this case)
So in light of this increasing period to 12 hours, and number of evalution periods to compare to alarm points.

Update billing alarm

---

terragrunt/aws/config/iam.tf

The Landing Zone has attached a role to our managed policy that cannot
be removed due to an org SCP.  As a result, the attachment is being
added to the Terraform to prevent future `terraform apply` failures.
* #145

chore: add AWS-Landing-Zone-ConfigRecorderRole

---

terragrunt/aws/central_account/s3.tf

Add the IAM role used in the Org Level Cloud Trail account from Control
Tower.
This work is already done on the Cloud Trail side of things, and this
just allows that to replicate to this bucket.

feat: add Org Cloud Trail replication role from CT

---

terragrunt/aws/central_account/kms.tf
terragrunt/aws/central_account/s3.tf
terragrunt/aws/central_account/sns.tf

Add an SNS topic to the central log archive account as this is now the mechanism CBS uses to invoke the transport lambda.
- #176

fix: create SNS topic for transport lambda

---

terragrunt/aws/alarms/alarms.tf

Increase alarm threshold to trigger if there's a 30 minutes period with low log counts.
- #187

chore: increase no logs alarm threshold

---

.github/workflows/export-github-data.yml

Export GitHub metadata to Sentinel.
- cds-snc/platform-core-services#204

feat: add GitHub metadata exporter

---

.github/workflows/export-github-data.yml

Update GitHub exporter workflow to include checkout step.
- cds-snc/platform-core-services#204

fix: add checkout to GitHub exporter workflow

---

terragrunt/aws/alarms/sns.tf

Update the CloudWatch SNS topics to post directly
to the SRE Bot when there is an alarm notification.

fix: use SRE Bot to post CloudWatch alarms

---

terragrunt/aws/satellite_bucket/s3.tf

Add a lifecycle rule to the CBS satellite access log bucket that deletes old objects after 90 days.  This will help reduce the size of these buckets while still give us time to investigate logs if needed.

feat: add s3 object lifecycle rule to access logs

---

.github/workflows/retrieve-accounts.yml

Update the deprecated set-output GitHub workflow commands to use the [new syntax](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter).

chore: fix deprecated workflow set-output commands

---

terragrunt/aws/satellite_bucket/s3.tf

Update the logging configuration on the satellite bucket to include a target_prefix for the access logs.
This was previously an optional parameter for the API that is now required:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_LoggingEnabled.html#AmazonS3-Type-LoggingEnabled-TargetPrefix

fix: add target_prefix to satellite bucket access logs

---

terragrunt/aws/central_account/s3.tf

Fixing the previous PR where the bucket policy was overwritten since it needs to be a single resource

fix: overwritten bucket policy
